/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaptiongritRouteImport } from './routes/captiongrit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ServicesConversionRouteImport } from './routes/services.conversion'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as ServicesAttentionRouteImport } from './routes/services.attention'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptiongritRoute = CaptiongritRouteImport.update({
  id: '/captiongrit',
  path: '/captiongrit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConversionRoute = ServicesConversionRouteImport.update({
  id: '/services/conversion',
  path: '/services/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/services/automation',
  path: '/services/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAttentionRoute = ServicesAttentionRouteImport.update({
  id: '/services/attention',
  path: '/services/attention',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/captiongrit': typeof CaptiongritRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services/attention': typeof ServicesAttentionRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/conversion': typeof ServicesConversionRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/captiongrit': typeof CaptiongritRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services/attention': typeof ServicesAttentionRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/conversion': typeof ServicesConversionRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/captiongrit': typeof CaptiongritRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/services/attention': typeof ServicesAttentionRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/conversion': typeof ServicesConversionRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/captiongrit'
    | '/contact'
    | '/pricing'
    | '/services/attention'
    | '/services/automation'
    | '/services/conversion'
    | '/work/$slug'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/captiongrit'
    | '/contact'
    | '/pricing'
    | '/services/attention'
    | '/services/automation'
    | '/services/conversion'
    | '/work/$slug'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/captiongrit'
    | '/contact'
    | '/pricing'
    | '/services/attention'
    | '/services/automation'
    | '/services/conversion'
    | '/work/$slug'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaptiongritRoute: typeof CaptiongritRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  ServicesAttentionRoute: typeof ServicesAttentionRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesConversionRoute: typeof ServicesConversionRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captiongrit': {
      id: '/captiongrit'
      path: '/captiongrit'
      fullPath: '/captiongrit'
      preLoaderRoute: typeof CaptiongritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/conversion': {
      id: '/services/conversion'
      path: '/services/conversion'
      fullPath: '/services/conversion'
      preLoaderRoute: typeof ServicesConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/services/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/attention': {
      id: '/services/attention'
      path: '/services/attention'
      fullPath: '/services/attention'
      preLoaderRoute: typeof ServicesAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaptiongritRoute: CaptiongritRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  ServicesAttentionRoute: ServicesAttentionRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesConversionRoute: ServicesConversionRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
